# PrefixをC-fに変更
set -g prefix C-f
unbind C-b

# tmux起動時のシェルをzshに設定
set-option -g default-shell /bin/zsh

# 256色表示可能に変更
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",$TERM:Tc"

# ESC入力に対するレスポンス時間を0msecに変更
set -s escape-time 0

# マウス操作を有効化
set -g mouse on

# status表示位置をTopに変更
set-option -g status-position top

# statusの表示を中央揃えに変更
set-option -g status-justify centre

# statusのバックグランド、文字列の色を指定
set-option -g status-bg black
set-option -g status-fg white

# status(左側)のフォーマットの変更
set-option -g status-left ""

# status(右側)のフォーマットの変更
set-option -g status-right ""

# status(中央)のフォーマットの変更
set-window-option -g window-status-format "#I:#W"

# status(中央)のカレントウィンドウのフォーマットを変更
set-window-option -g window-status-current-format "#[fg=colour255,bg=colour27,bold]#I:#W"

# ウィンドウの開始番号を1からに変更
set-window-option -g base-index 1

# ウィンドウを閉じたらインデックス番号を振り直すように変更
set-option -g renumber-windows on

# .tmux.confの再読み込み
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# ペインを縦横に分割
bind v split-window -h
bind s split-window -v

# ペインの移動をVim風に変更
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ペインのサイズ変更をVim風に変更
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# コピーモードの操作をVim風に変更
set-window-option -g mode-keys vi

# クリップボードへコピーするように変更
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# マウスでドラッグ&ドロップでクリップボードへコピーできるように変更
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# コピーモードをenter入力で抜けれるように変更
bind Enter copy-mode
